steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - infra/docker/ingest.Dockerfile
      - -t
      - europe-west12-docker.pkg.dev/signal-ac219/signal-containers/signal-ingest:staging
      - .
images:
  - europe-west12-docker.pkg.dev/signal-ac219/signal-containers/signal-ingest:staging
